/**
 * Combat Results Builder
 * Constructs EnhancedCombatResult from CombatScene state
 */

import { EnhancedCombatResult } from '../EventBridge'

interface UnitData {
  id: string
  name: string
  team: 'blue' | 'red'
  hp: number
  maxHp: number
  injuries?: any[]
}

interface CombatStats {
  damageByUnit: Record<string, {
    dealt: number
    taken: number
    kills: number
    shots: number
    hits: number
    team: 'blue' | 'red'
  }>
  killLog: Array<{
    killer: string
    victim: string
    weapon: string
    damage: number
  }>
  totalDamageDealt: { blue: number; red: number }
  shotsFired: { blue: number; red: number }
  hits: { blue: number; red: number }
}

/**
 * Build enhanced combat result from scene data
 */
export function buildEnhancedCombatResult(
  winner: 'blue' | 'red',
  rounds: number,
  units: Map<string, UnitData>,
  combatStats: CombatStats,
  missionContext?: {
    sector: string
    city: string
    country: string
  }
): EnhancedCombatResult {
  const victory = winner === 'blue'

  // Collect casualties (dead or unconscious)
  const casualties: EnhancedCombatResult['casualties'] = []
  const survivors: EnhancedCombatResult['survivors'] = []
  const injuries: EnhancedCombatResult['injuries'] = []

  units.forEach((unit) => {
    if (unit.hp <= 0) {
      // Find who killed this unit
      const killEntry = combatStats.killLog.find(k => k.victim === unit.name)

      casualties.push({
        characterId: unit.id,
        characterName: unit.name,
        status: 'dead', // Could be 'unconscious' based on injury system
        killedBy: killEntry?.killer
      })
    } else {
      // Survivor
      const unitStats = combatStats.damageByUnit[unit.name] || {
        dealt: 0,
        taken: 0,
        kills: 0,
        shots: 0,
        hits: 0,
        team: unit.team
      }

      survivors.push({
        characterId: unit.id,
        characterName: unit.name,
        currentHp: unit.hp,
        maxHp: unit.maxHp,
        damageDealt: unitStats.dealt,
        damageTaken: unitStats.taken,
        kills: unitStats.kills
      })
    }

    // Collect injuries from combat
    if (unit.injuries && unit.injuries.length > 0) {
      unit.injuries.forEach((injury: any) => {
        injuries.push({
          characterId: unit.id,
          characterName: unit.name,
          bodyPart: injury.bodyPart || 'torso',
          severity: injury.severity || 'MODERATE',
          description: injury.description || `${injury.type} injury`,
          healingTime: injury.healingDays || 0,
          permanent: injury.permanent || false
        })
      })
    }
  })

  // Calculate XP (will be refined by combatResultsHandler)
  const experienceGained = survivors.map(survivor => ({
    characterId: survivor.characterId,
    characterName: survivor.characterName,
    xp: 0, // Will be calculated by handler
    reason: 'combat'
  }))

  // Calculate combat time elapsed
  // Assume ~5-10 minutes per round
  const timeElapsed = rounds * (5 + Math.floor(Math.random() * 5))

  // Calculate accuracy rate
  const totalShots = combatStats.shotsFired.blue + combatStats.shotsFired.red
  const totalHits = combatStats.hits.blue + combatStats.hits.red
  const accuracyRate = totalShots > 0 ? totalHits / totalShots : 0

  // Estimate collateral damage (rough approximation)
  // More shots fired = more collateral damage
  const collateralDamage = Math.floor(totalShots * 500 + Math.random() * 5000)

  // Civilian casualties (random, low chance)
  const civilianCasualties = Math.random() < 0.1 ? Math.floor(Math.random() * 3) : 0

  // Calculate fame change (will be refined by handler)
  const baseFame = victory ? 15 : -20
  const fameChange = baseFame - (civilianCasualties * 10) - Math.floor(collateralDamage / 10000)

  const result: EnhancedCombatResult = {
    victory,
    winner,
    rounds,
    timeElapsed,
    casualties,
    injuries,
    survivors,
    experienceGained,
    lootGained: [], // Will be generated by handler
    fameChange,
    publicOpinionChange: {},
    missionLocation: missionContext,
    totalDamageDealt: combatStats.totalDamageDealt.blue + combatStats.totalDamageDealt.red,
    totalDamageTaken: combatStats.totalDamageDealt.blue + combatStats.totalDamageDealt.red,
    accuracyRate,
    collateralDamage,
    civilianCasualties
  }

  return result
}

/**
 * Log combat result summary to console
 */
export function logCombatResultSummary(result: EnhancedCombatResult): void {
  console.log('='.repeat(60))
  console.log('COMBAT RESULTS SUMMARY')
  console.log('='.repeat(60))
  console.log(`Outcome: ${result.victory ? 'VICTORY' : 'DEFEAT'} (${result.winner} team wins)`)
  console.log(`Duration: ${result.rounds} rounds (${result.timeElapsed} minutes)`)
  console.log(`Accuracy: ${(result.accuracyRate * 100).toFixed(1)}%`)
  console.log()
  console.log(`Casualties: ${result.casualties.length}`)
  result.casualties.forEach(c => {
    console.log(`  - ${c.characterName} (${c.status})${c.killedBy ? ` killed by ${c.killedBy}` : ''}`)
  })
  console.log()
  console.log(`Survivors: ${result.survivors.length}`)
  result.survivors.forEach(s => {
    console.log(`  - ${s.characterName}: ${s.currentHp}/${s.maxHp} HP, ${s.kills} kills, ${s.damageDealt} dmg`)
  })
  console.log()
  console.log(`Injuries: ${result.injuries.length}`)
  result.injuries.forEach(inj => {
    console.log(`  - ${inj.characterName}: ${inj.severity} ${inj.bodyPart} - ${inj.description}`)
  })
  console.log()
  console.log(`Fame Change: ${result.fameChange > 0 ? '+' : ''}${result.fameChange}`)
  console.log(`Collateral Damage: $${result.collateralDamage?.toLocaleString() || 0}`)
  console.log(`Civilian Casualties: ${result.civilianCasualties || 0}`)
  console.log('='.repeat(60))
}
